Solucao provisoria parao social recycler view
gabeira/Plantare pull request #15
Opened 2016-10-13 22:38 UTC by jbalves

@gabeira @firemanxbr @DanielNogueiraAndroid @gleidesigner @Wandersonjack

2016-10-15 00:07 UTC, gabeira requested changes
Also remember to reformat the code
Menu>Code>Reformat Code
To keep it better organized.
And congratulations for the feature.

2016-10-15 00:07 UTC, gabeira commented on app/src/main/java/mobi/plantare/fragments/SocialFragment.java
> +        /*
Remove comments

2016-10-15 00:07 UTC, gabeira commented on app/src/main/java/mobi/plantare/fragments/SocialFragment.java
> +                //mclusterManager.cluster();
Add 
`adapter.notifyDataSetChanged();`

2016-10-15 00:07 UTC, gabeira commented on app/src/main/java/mobi/plantare/fragments/SocialFragment.java
> +        ArrayList<Plant> lista = getPlants();
Declare as a class variable and use once.

2016-10-15 00:07 UTC, gabeira commented on app/src/main/java/mobi/plantare/adapters/SocialListAdapter.java
> +            /* Ainda não está funcionando o set de imagens das plantas
Forget Glide here, you already have the bitmap, just load it.
`imgPlantView.setImageBitmap(bmp);`

2016-10-15 00:07 UTC, gabeira commented on app/src/main/java/mobi/plantare/adapters/SocialListAdapter.java
> +            if (imgPlantView == null) return this;
Check also for imageBytes == null
Than load another placeholder image like iplanted2

2016-10-15 00:07 UTC, gabeira commented on app/src/main/res/layout/item_social_list.xml
> +        android:background="@mipmap/ic_launcher"/>
Remove background, rather will have both images
Maybe just another color meaning that will load an image there.

2016-10-15 00:07 UTC, gabeira commented on app/src/main/res/layout/item_social_list.xml
> +    <ImageView
Will be nice to set an scaleType as well.

2016-10-25 00:37 UTC, gabeira approved these changes

2016-11-03 22:28 UTC, gleideveloper approved these changes
Done

2016-11-10 02:10 UTC, merged