daniel/refactory_split_methods_on_garden
gabeira/Plantare pull request #18
Opened 2017-01-25 18:52 UTC by DanielNogueiraAndroid

update gradle dependencies version
tiny refactor to get the GardenMapFragment more easy to read

2017-01-27 09:09 UTC, gabeira approved these changes

2017-02-02 09:22 UTC, gabeira requested changes
Please describe the Pull Request Title (what this PR do?), do not use branch name.

2017-02-02 17:43 UTC, Itapirema approved these changes

2017-02-05 12:07 UTC, gabeira approved these changes

2017-02-05 12:08 UTC, merged