Improved Firebase objects and login for Facebook, created Tutorial
gabeira/Plantare pull request #19
Opened 2017-01-27 12:32 UTC by gabeira

2017-01-27 15:03 UTC, DanielNogueiraAndroid requested changes
Tudo ok se possivel por favor fazer aquela pequena correção do Map só para não quebrar a build

2017-01-27 15:03 UTC, DanielNogueiraAndroid commented on app/build.gradle
> +    compile "com.google.maps.android:android-maps-utils:0.4.4"
Muito bom atulizar o Gradle !!
precisamos de fix antes de ir para master 
com o update de "com.google.maps.android:android-maps-utils:0.4.4" 
na classe GardenMapFragment o metodo map.setOnCameraChangeListener(mClusterManager); 
precisa ser alterado para map.setOnCameraIdleListener(mClusterManager);
nas linhas 386 e 352, 
Acho que a build quebra se não fizer isso.

2017-01-30 11:42 UTC, gabeira commented on app/build.gradle
> +    compile "com.google.maps.android:android-maps-utils:0.4.4"
Não mudei o GardenMapFragment para não dar conflito com teu PR

2017-01-30 11:55 UTC, DanielNogueiraAndroid commented on app/build.gradle
> +    compile "com.google.maps.android:android-maps-utils:0.4.4"
Entendi!
Mas pode alterar sim depois resolvemos o conflito se você puder ma ajudar.
Pode ser ?

2017-02-01 11:29 UTC, gabeira commented on app/build.gradle
> +    compile "com.google.maps.android:android-maps-utils:0.4.4"
Done, please check

2017-02-02 15:39 UTC, Itapirema approved these changes
That's all right!

2017-02-02 17:31 UTC, DanielNogueiraAndroid approved these changes

2017-02-03 03:04 UTC, merged